### ISSUE TITLE
06-SQL-04-"Manipuleren en Definiëren": Solutions include SQL Server syntax

### ISSUE THREAD

**Issue by Liwago** [HOGENT-Databases/DB1-Workshops#23]
The solutions for the exercises on Manipulating and Defining DB's include the "_identity(1,1)_" property, which is specific to SQL Server. We, the students, work with MySQL.

Example:
`kleurID int IDENTITY(1, 1) NOT NULL PRIMARY KEY,`

Proposed solutions: 
- change to "**AUTO_INCREMENT**".
- add "**AUTO_INCREMENT**" and keep both.

**Comment by vertonghenb** [comment]
@correct, fixed by #24
