### ISSUE TITLE
04-relationeel_model exercises exercise-7

### ISSUE THREAD

**Issue by SibianDG** [HOGENT-Databases/DB1-Workshops#34]
Oplossing:
- I(t1,i1, o1)​
-     t1 VS wijst naar t1 in T; verplicht​
-     o1 VS wijst naar o1 in O; optioneel​
- O(o1,o2, t1)​
-     t1 VS wijst naar t1 in I; verplicht

Bij een 1 op 1: vreemde sleutel aan 1 zijde (zelf te kiezen), maar hier staat het dubbel. in O verwijst u naar I en in I verwijst u naar O. Moet het niet zijn één van de twee kanten zijn i.v.p. beide?

**Comment by vertonghenb** [comment]
Klopt, het is ook aangewezen om de vreemde sleutel langs de "O" kant te plaatsen. Dit in het kader van minder NULL waarden.
