### ISSUE TITLE
Het sql script van planten is niet correct verbetering in attachments

### ISSUE THREAD

**Issue by vkqenz** [HOGENT-Databases/DB1-Workshops#49]
[https://github.com/HOGENT-Databases/DB1-Workshops/blob/master/databases/planten.sql](url)

[plantenfixed.zip](https://github.com/HOGENT-Databases/DB1-Workshops/files/5601553/plantenfixed.zip)

**Comment by vertonghenb** [comment]
Thanks, merged!
