### ISSUE TITLE
SQL: opdracht 7 bij combineren (dranken)

### ISSUE THREAD

**Issue by hdpr** [HOGENT-Databases/DB1-Workshops#50]
7. Welke artikelen werden verkocht onder de adviesverkoopprijs? Geef artikelnummer, soortnummer en productnaam.
    > 35 records
    ```sql
    SELECT a.artikelnr, s.soortnr, p.productnaam
    FROM artikel a  
        JOIN factuurregel f ON a.artikelnr=f.artikelnr
        JOIN soort s ON a.soortnr = s.soortnr
            JOIN productgroep p ON s.productgroepnr = p. productgroepnr
    WHERE a.adviesverkoopprijs > verkoopprijs/aantal;

Ik zou de verkoopprijs niet delen door aantal???

**Comment by jorenvermeersch** [comment]
Ik heb de verkoopprijs ook niet gedeeld door het aantal gezien dit geen procesgegeven is. De INNER JOIN tussen soort en productgroep is ook overbodig. Alle nodige gegevens kunnen opgevraagd worden uit artikel en soort. 

Dit is mijn oplossing:

```
SELECT a.artikelnr, a.soortnr, s.naam
	FROM artikel AS a
		JOIN factuurregel AS f ON a.artikelnr = f.artikelnr
                JOIN soort AS s ON a.soortnr = s.soortnr
	WHERE a.adviesverkoopprijs > f.verkoopprijs;
```

**Comment by hdpr** [comment]
De opdracht stelt: geef artikelnummer, soortnummer én **productnaam** = join met productgroep is wel nodig

**Comment by vertonghenb** [comment]
Fixed.
