### ISSUE TITLE
afdelingshoofd

### ISSUE THREAD

**Issue by AngelineVanAchter** [HOGENT-Databases/DB1-Workshops#9]
je schrijft dat het telefoonnummer er gewoon bijkomt. In de opgave staat dat het een uniek telnr is voor de afdeling  wordt volgens mij kandidaatsleutel.

**Comment by vertonghenb** [comment]
Klopt, volledig mee eens, was allicht aan het denken aan een `Primary Key` in plaats van een `kandidaatsleutelattribuuttype`.

Uitleg:
Je kan perfect meerdere kandidaatsleutels hebben in het conceptueel model (ERD). Later in het relationele model, heb je slechts 1 primary key.
